version: '3.7'

networks:
  default:
    name: Digital-Transformation-Leaders
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

  web:
    build: .
    command: uvicorn app.main:create_app --host 0.0.0.0 --port 8001
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
