"""update migration

Revision ID: 61e9a3f63f35
Revises: 686720d30be6
Create Date: 2023-05-28 18:32:19.678399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e9a3f63f35'
down_revision = '686720d30be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
