"""create relationship between mkb and services

Revision ID: 686720d30be6
Revises: 
Create Date: 2023-05-28 18:19:48.624407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686720d30be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mkb_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_code_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('treatment_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mkb_id', sa.Integer(), nullable=True),
    sa.Column('service_code_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mkb_id'], ['mkb_table.id'], ),
    sa.ForeignKeyConstraint(['service_code_id'], ['service_code_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_course')
    op.drop_table('users')
    op.drop_table('service_code_table')
    op.drop_table('mkb_table')
    # ### end Alembic commands ###
