name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy source code to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/Digital-Transformation-Leaders-2023/backend"

    - name: Build and Run Docker Image on Remote Server
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |          
          cd /Digital-Transformation-Leaders-2023/backend
          docker-compose down --remove-orphans -v
          docker-compose up --build -d
