name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest tests/test_main.py

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag myapp2:$(date +%s)

    - name: Copy source code to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/Digital-Transformation-Leaders-2023/backend"

    - name: Build and Run Docker Image on Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /Digital-Transformation-Leaders-2023/backend
          docker build -t myapp2 .
          if [ "$(docker ps -q -f name=myapp2)" ]; then
            docker stop myapp2 && docker rm myapp2
          fi
          docker run -d --name myapp2 -p 8001:8001 myapp2
